import type { Section } from "../types";

export const laboratorySchema: Section[] = [
  {
    title: "HAEMATOLOGY",
    tests: [
      { priorityDe: 1, name: "HB" },
      { priorityDe: 2, name: "RBC Count" },
      { priorityDe: 3, name: "TLC" },
      { priorityDe: 4, name: "Platelets Count" },
      { priorityDe: 5, name: "DLC" },
      { priorityDe: 6, name: "ESR" },
      { priorityDe: 8, name: "MCV" },
      { priorityDe: 9, name: "MCH" },
      { priorityDe: 10, name: "MCHC" },
      { priorityDe: 11, name: "RDW" },
      { priorityDe: 12, name: "Blood Group & Rh Type" },
      { priorityDe: 13, name: "Coombs test" },
      { priorityDe: 14, name: "Retics" },
      { priorityDe: 15, name: "PBS / PBF" },
      { priorityDe: 16, name: "HbA1c" },
      { priorityDe: 17, name: "Special Stain", name2: "MPO" },
      { priorityDe: 18, name: "", name2: "PAS" },
      { priorityDe: 19, name: "Sickling Test" },
      { priorityDe: 20, name: "Urine for Hemosiderin" },
      { priorityDe: 21, name: "BT" },
      { priorityDe: 22, name: "CT" },
      { priorityDe: 23, name: "PT-INR" },
      { priorityDe: 24, name: "APTT" },
      { priorityDe: 25, name: "Bone Marrow Analysis" },
      { priorityDe: 26, name: "Aldehyde Test" },
      { priorityDe: 27, name: "MP Total" },
      { priorityDe: 28, name: "Smear MP Pos.", name2: "PF" },
      { priorityDe: 29, name: "", name2: "PV" },
      { priorityDe: 30, name: "", name2: "P-MIX" },
      { priorityDe: 31, name: "ME", name2: "Total" },
      { priorityDe: 32, name: "", name2: "Pos." },
      { priorityDe: 33, name: "LD Bodies" },
      { priorityDe: 34, name: "Hb Electrophoresis" },
      { priorityDe: 35, name: "LE cell" },
      { priorityDe: 36, name: "ALC" },
      { priorityDe: 37, name: "AEF" },
      { priorityDe: 38, name: "FDP" },
      { priorityDe: 39, name: "D-dimer" },
      { priorityDe: 40, name: "Fac VIII" },
      { priorityDe: 41, name: "Fac IX" },
      { priorityDe: 42, name: "Cross Matching" },
      { priorityDe: 43, name: "Others" },
    ],
  },
  {
    title: "IMMUNOLOGY",
    tests: [
      { priorityDe: 44, name: "Pregnancy Test (UPT)" },
      { priorityDe: 45, name: "ASO" },
      { priorityDe: 46, name: "CRP" },
      { priorityDe: 47, name: "RA Factor" },
      { priorityDe: 48, name: "TPHA", name2: "Total" },
      { priorityDe: 49, name: "", name2: "+ Ve" },
      { priorityDe: 50, name: "ANA" },
      { priorityDe: 51, name: "Anti-dsDNA" },
      { priorityDe: 52, name: "PRP / VDRL", name2: "Total" },
      { priorityDe: 53, name: "", name2: "+ Ve" },
      { priorityDe: 54, name: "CEA" },
      { priorityDe: 55, name: "CA-125" },
      { priorityDe: 56, name: "CA-19.9" },
      { priorityDe: 57, name: "CA-15.5" },
      { priorityDe: 58, name: "Toxo" },
      { priorityDe: 59, name: "CMV" },
      { priorityDe: 60, name: "Toxo Rubella" },
      { priorityDe: 61, name: "CMV" },
      { priorityDe: 62, name: "Measles" },
      { priorityDe: 63, name: "Echinococcus" },
      { priorityDe: 64, name: "Amoebiasis" },
      { priorityDe: 65, name: "PSA" },
      { priorityDe: 66, name: "Ferritin" },
      { priorityDe: 67, name: "Cysticercosis" },
      { priorityDe: 68, name: "Brucella" },
      { priorityDe: 69, name: "Thyroglobulin" },
      { priorityDe: 70, name: "Anti TPO" },
      { priorityDe: 71, name: "Protein Electrophoresis" },
      { priorityDe: 72, name: "Anti-CCP" },
      { priorityDe: 73, name: "RK-39", name2: "Total" },
      { priorityDe: 74, name: "", name2: "+Ve" },
      { priorityDe: 75, name: "JE", name2: "Total" },
      { priorityDe: 76, name: "", name2: "+Ve" },
      { priorityDe: 77, name: "Dengue", name2: "Total" },
      { priorityDe: 79, name: "Rapid MP test", name2: "Total" },
      { priorityDe: 80, name: "", name2: "+ Ve PV" },
      { priorityDe: 81, name: "", name2: "+ Ve PF" },
      { priorityDe: 82, name: "", name2: "+ Ve P-Mix" },
      { priorityDe: 83, name: "Mantoux test" },
      { priorityDe: 84, name: "Chikungunya", name2: "Total" },
      { priorityDe: 85, name: "", name2: "+Ve PV" },
      { priorityDe: 86, name: "", name2: "Scrub Typhus" },
      { priorityDe: 87, name: "", name2: "H. Pylori" },
      { priorityDe: 88, name: "Leptospira" },
      { priorityDe: 89, name: "Widal Test" },
      { priorityDe: 90, name: "Others" },
    ],
  },
  {
    title: "BIOCHEMISTRY",
    tests: [
      { priorityDe: 91, name: "Sugar" },
      { priorityDe: 92, name: "Blood Urea" },
      { priorityDe: 93, name: "Creatinine" },
      { priorityDe: 94, name: "Sodium (Na)" },
      { priorityDe: 95, name: "Potassium (K)" },
      { priorityDe: 96, name: "Calcium" },
      { priorityDe: 97, name: "Phosphorus" },
      { priorityDe: 98, name: "Magnesium" },
      { priorityDe: 99, name: "Uric acid" },
      { priorityDe: 100, name: "Total Cholesterol" },
      { priorityDe: 101, name: "Triglycerides" },
      { priorityDe: 102, name: "HDL" },
      { priorityDe: 103, name: "LDL" },
      { priorityDe: 104, name: "Amylase" },
      { priorityDe: 105, name: "Micro albumin" },
      { priorityDe: 106, name: "Bilirubin" },
      { priorityDe: 107, name: "SGPT" },
      { priorityDe: 108, name: "Alk Phos" },
      { priorityDe: 109, name: "SGOT" },
      { priorityDe: 110, name: "Total Protein" },
      { priorityDe: 111, name: "Gamma GT" },
      { priorityDe: 112, name: "24hr Urine Protein" },
      { priorityDe: 113, name: "24hr urine U/A" },
      { priorityDe: 114, name: "Creatinine Clearance" },
      { priorityDe: 115, name: "Iron" },
      { priorityDe: 116, name: "TIBC" },
      { priorityDe: 117, name: "CPK-MB" },
      { priorityDe: 118, name: "CPK-NAC" },
      { priorityDe: 119, name: "LDH" },
      { priorityDe: 120, name: "Iso-Trop-I" },
      { priorityDe: 121, name: "Other" },
    ],
  },
  {
    title: "BACTERIOLOGY",
    tests: [
      { priorityDe: 122, name: "Gram Stain" },
      { priorityDe: 123, name: "Culture", name2: "Blood" },
      { priorityDe: 124, name: "", name2: "Urine" },
      { priorityDe: 125, name: "", name2: "Body Fluid" },
      { priorityDe: 126, name: "", name2: "Swab" },
      { priorityDe: 127, name: "Culture", name2: "Stool" },
      { priorityDe: 128, name: "", name2: "Water" },
      { priorityDe: 129, name: "", name2: "Pus" },
      { priorityDe: 130, name: "", name2: "Sputum" },
      { priorityDe: 131, name: "", name2: "CSF" },
      { priorityDe: 132, name: "", name2: "Others" },
      { priorityDe: 133, name: "Sputum AFB" },
      { priorityDe: 134, name: "Other AFB" },
      { priorityDe: 135, name: "Leprosy Smear" },
      { priorityDe: 136, name: "India Ink Test" },
      { priorityDe: 137, name: "Anaerobic Culture" },
      { priorityDe: 138, name: "Fungus", name2: "KOH Test" },
      { priorityDe: 139, name: "", name2: "Culture" },
      { priorityDe: 140, name: "Others" },
    ],
  },
  {
    title: "VIROLOGY",
    tests: [
      { priorityDe: 141, name: "HIV RDT", name2: "Total" },
      { priorityDe: 142, name: "", name2: "+ Ve" },
      { priorityDe: 143, name: "HBsAg RDT", name2: "Total" },
      { priorityDe: 144, name: "", name2: "+ Ve" },
      { priorityDe: 145, name: "HCV RDT", name2: "Total" },
      { priorityDe: 146, name: "", name2: "+ Ve" },
      { priorityDe: 147, name: "HAV ELISA/CLIA", name2: "Total" },
      { priorityDe: 148, name: "", name2: "+ Ve" },
      { priorityDe: 149, name: "HBsAg ELISA/CLIA", name2: "Total" },
      { priorityDe: 150, name: "", name2: "+ Ve" },
      { priorityDe: 151, name: "HCV ELISA/CLIA", name2: "Total" },
      { priorityDe: 152, name: "", name2: "+ Ve" },
      { priorityDe: 153, name: "HEV ELISA/CLIA", name2: "Total" },
      { priorityDe: 154, name: "", name2: "+ Ve" },
      { priorityDe: 155, name: "HEV ELISA/CLIA", name2: "Total" },
      { priorityDe: 156, name: "", name2: "+ Ve" },
      { priorityDe: 157, name: "Anti HBs" },
      { priorityDe: 158, name: "HBeAg" },
      { priorityDe: 159, name: "Anti HBe" },
      { priorityDe: 160, name: "HBcAg" },
      { priorityDe: 161, name: "Anti HBcAg" },
      { priorityDe: 162, name: "Western Blot" },
      { priorityDe: 163, name: "CD4 Count" },
      { priorityDe: 164, name: "Viral Load" },
      { priorityDe: 165, name: "Others" },
    ],
  },
  {
    title: "PARASITOLOGY",
    tests: [
      { priorityDe: 166, name: "Stool R/E" },
      { priorityDe: 167, name: "Occult blood" },
      { priorityDe: 168, name: "Reducing sugar" },
      { priorityDe: 169, name: "Urine R/E" },
      { priorityDe: 170, name: "Bile salts" },
      { priorityDe: 171, name: "Bile pigments" },
      { priorityDe: 172, name: "Urobilinogen" },
      { priorityDe: 173, name: "Porphobilinogen" },
      { priorityDe: 174, name: "Acetone" },
      { priorityDe: 175, name: "Chyle" },
      { priorityDe: 176, name: "Specific Gravity" },
      { priorityDe: 177, name: "Bence Jones Protin" },
      { priorityDe: 178, name: "Semen analysis" },
      { priorityDe: 179, name: "Others" },
    ],
  },
  {
    title: "HORMONE / ENDOCRINE",
    tests: [
      { priorityDe: 180, name: "T3" },
      { priorityDe: 181, name: "T4" },
      { priorityDe: 182, name: "TSH" },
      { priorityDe: 183, name: "Cortisol" },
      { priorityDe: 184, name: "AFP" },
      { priorityDe: 185, name: "LH" },
      { priorityDe: 186, name: "FSH" },
      { priorityDe: 187, name: "Prolactin" },
      { priorityDe: 188, name: "Oestrogen" },
      { priorityDe: 189, name: "Progesterone" },
      { priorityDe: 190, name: "Testosterone" },
      { priorityDe: 191, name: "Vit. D" },
      { priorityDe: 192, name: "Vit. B12" },
      { priorityDe: 193, name: "Others" },
    ],
  },
  {
    title: "DRUG ANALYSIS",
    tests: [
      { priorityDe: 194, name: "Carbamazepine" },
      { priorityDe: 195, name: "Cyclosporine" },
      { priorityDe: 196, name: "Valproic acid" },
      { priorityDe: 197, name: "Phenytoin" },
      { priorityDe: 198, name: "Digoxine" },
      { priorityDe: 199, name: "Tacrolimus" },
      { priorityDe: 200, name: "Others" },
    ],
  },
  {
    title: "HISTOPATHOLOGY/CYTOLOGY",
    tests: [
      { priorityDe: 201, name: "Biopsy", name2: "H&E" },
      { priorityDe: 202, name: "", name2: "H&Others" },
      { priorityDe: 203, name: "Cytology", name2: "Pap" },
      { priorityDe: 204, name: "", name2: "Giemsa" },
      { priorityDe: 205, name: "Others" },
    ],
  },
  {
    title: "IMMUNO-HISTO CHEMISTRY",
    tests: [
      { priorityDe: 206, name: "ER" },
      { priorityDe: 207, name: "PR" },
      { priorityDe: 208, name: "G-FAP" },
      { priorityDe: 209, name: "S-100" },
      { priorityDe: 210, name: "Vimentin" },
      { priorityDe: 211, name: "Cytokeratin" },
      { priorityDe: 212, name: "Others" },
    ],
  },
  {
    title: "MOLECULAR LAB & FLOWCYTOMETRY",
    tests: [
      { priorityDe: 213, name: "Covid-19 PCR" },
      { priorityDe: 214, name: "Influenza" },
      { priorityDe: 215, name: "Leukemia Panel" },
    ],
  },
];
